
questiondata["Math_Methods"]=[
//Misc
{q:"Expand $\\cosh(a+b)$ and $\\sinh(a+b)$.",a:"$\\cosh(a+b)=\\cosh(a)\\cosh(b)+\\sinh(a)\\sinh(b)$ and $\\sinh(a+b)=\\cosh(a)\\sinh(b)+\\sinh(a)\\cosh(b)$"},
//Indefinite integrals
{q:"Find $I=\\int_{-\\infty}^{\\infty}\\frac{x \\sin(x)}{x^2+2x+2}$.",a:"$\\frac{\\pi}{e}(\\sin(1)+\\cos(1))$. To prove this, consider $\\int_{-\\infty}^{\\infty}\\frac{x e^{ix}}{x^2+2x+2}$. To evaluate this, take a contour integral from $x=-R$ to $x=R$, then around in a circle $x=R e^{i\\theta}$. The circle part is exponentially suppressed. This region is traversed clockwise and contains a simple pole at $-1+i$, so we have: $$2\\pi i \\text{Res}_{z=-1+i}\\frac{x e^{ix}}{x^2+2x+2}=\\int_{-\\infty}^{\\infty}\\frac{x e^{ix}}{x^2+2x+2}$$ The residue is equal to $\\frac{(-1+i)}{-1+i+1+i}e^{i(-1+i)}$, and taking the imaginary part of both sides gives the desired formula."},
{q:"Find the Fresnel integrals $\\int_{0}^\\infty \\cos(x^2)dx=\\int_{0}^\\infty \\sin(x^2)dx$",a:"Both are equal to $\\frac{\\pi}{2\\sqrt{2}}$. A suitable contour of $\\int_\\gamma e^{iz^2}dz$ will give us the result. Choose the $45^\\circ$ circular wedge: $0\\to R\\to \\frac{R}{\\sqrt{2}}(1+i)\\to 0$. (note $\\frac{1}{\\sqrt{2}}(1+i)=\\sqrt{i}$). The circular part is suppressed and no poles are contained, so we wind up with: $$0=\\int_{0}^\\infty e^{i x^2}dx+\\int_{\\infty}^0 e^{i (x^2i)}dx\\frac{1}{\\sqrt{2}}(1+i)$$ but the integral of $e^{-x^2}$ from 0 to infinity is just $\\sqrt{\\pi}/2$, and swapping gives a negative sign, hence: $0=\\int_{0}^\\infty (\\cos(x^2)+i\\sin(x^2))dx-\\frac{\\sqrt{\\pi}}{2\\sqrt{2}}(1+i)$ giving us the result."},
{q:"Find the sinc integral $\\int_{0}^\\infty \\frac{\\sin(x)}{x}dx$.",a:"$\\pi/2$. To derive this, consider $\\int \\frac{e^{iz}}{z}$ over a contour from $-R$ to $-\\rho$, around in a clockwise circle to $+\\rho$ (avoiding and not encircling the pole), then to $+R$, then around in a counterclockwise circle to $-R$. The big circle is exponentially suppressed as $R\\to \\infty$ and the horizontal segments are the integral we're looking for times $i$ (the real part is zero, because $\\cos$ is an even function and $1/x$ is odd). The only confusing thing is the $\\rho\\to 0$ limit, but we can approximate $e^{iz}\\approx 1$. The resulting $1/z$ integral is then just $-i\\pi$, and we have $0=-i\\pi+2\\int_0^\\infty e^{i x^2}dx=-i\\pi+2i\\int_0^\\infty \\frac{\\sin(x)}{x}dx$."},
{q:"Calculate $I=\\int_{0}^\\infty \\frac{\\log(x)}{(x^2+4)^2} dx$ (Warning: there's a fair amount of algebra.)",a:"$\\frac{\\pi}{32}(\\log(2)-1)$. We have a limit $\\rho\\to 0$ and $R\\to \\infty$. Do a contour integral from $\\rho$ to $R$, positively in a circle to $-R$, then to -$\\rho$, then negatively in a circle to $+\\rho$. You find out that the $+R$ to $-R$ arc integral is suppressed by a power of $1/R^3$ so is zero in the limit, and the $-\\rho$ to $+\\rho$ limit is approximately $\\int \\log(z)dz=(z\\log(z)-z)_{-\\rho}^\\rho$. But the limit $\\lim_{z\\to 0}z\\log(z)=0$, so in fact the rho integral is zero as well. The first line segment is the integral $I$, and the last line segment is $\\int_{-R}^{-\\rho} \\frac{\\log(x)}{(x^2+4)^2 }dx=\\int_{\\rho}^R\\frac{\\log(x)+i \\pi}{(x^2+4)^2}dx=I+\\int_0^\\infty \\frac{i\\pi}{(x^2+4)^2}$. But this last integral is just $\\int_0^\\infty \\frac{i\\pi}{(x^2+4)^2}=i\\pi \\text{Res}_{z=2i}\\frac{i\\pi}{(x^2+4)^2}$. All-in-all, the residue theorem to this contour has told us: $$2\\pi i\\text{Res}_{z=2i} \\frac{\\log(x)}{(x^2+4)^2} =2I+2i\\pi \\text{Res}_{z=2i}\\frac{i\\pi/2}{(x^2+4)^2}$$ From which:  $$\\pi i\\text{Res}_{z=2i} \\frac{\\log(x)-i\\pi/2}{(x^2+4)^2} =I$$ We have a second order pole, so the residue can be evaluated with the limit formula: $$I=\\pi i\\frac{1}{1!} \\lim_{z\\to 2i} \\frac{d}{dz} (z-2i)^2 \\frac{\\log(z)-i\\pi/2}{(z^2+4)^2}=\\frac{\\pi}{32}(\\log(2)-1)$$"},
{q:"Calculate $I=\\int_0^\\infty \\frac{x^{-a}}{x+1}$ for $0\\lt a \\lt 1$.",a:"$\\frac{\\pi}{\\sin(\\pi a)}$. This is an exercise in exploiting branch cuts. Integrate $x$ along the contour from $x=\\rho$, to $x=R$ (so $x^{-a}=e^{-a\\log(R)}$), then around positively in a full circle to $x=R$ again (so that now $x^{-a}=e^{-a\\log(R)-2\\pi i a}$), back to $+\\rho$ ($x^{-a}=e^{-a\\log(\\rho)-2\\pi i a}$), then around negatively in a full circle to $+\\rho$ to close the contour. We find that the center 'keyhole' $\\rho$ integral is zero as $\\rho\\to 0$, and likewise the large circle is zero as $R\\to \\infty$. Our contour contains one pole at $x=-1$, so the residue theorem tells us: $$2\\pi I \\text{Res}_{z=-1} \\frac{x^{-a}}{x+1}=\\int_{0}^\\infty \\frac{x^{-a}}{x+1}dx+\\int_{\\infty}^0 \\frac{x^{-a} e^{-2\\pi i a}}{x+1}=I(1-e^{-2\\pi i a})$$ The residue on the relevant branch is $(-1)^{-a}=e^{-i\\pi a}$, so we have $I=\\frac{2\\pi i e^{-i\\pi a}}{1-e^{-2\\pi i a}}=\\frac{\\pi}{\\sin(\\pi a)}$"},
{q:"Calculate $I=\\int_{0}^{2\\pi} \\frac{d\\theta}{1+a\\sin(\\theta)}$ for $-1\\lt a\\lt 1$.",a:"$\\frac{2\\pi}{\\sqrt{1-a^2}}$. This can be solved by substituting $z=e^{i\\theta}$, from which $I=\\frac{2}{a}\\int_{\\gamma}\\frac{dz}{z^2+(2i/a) z-1}$. This has poles at $-\\frac{i}{a}(1\\pm\\sqrt{1-a^2})$. The $+$ pole clearly lies outside the unit circle. We also have $0\\le 1-\\sqrt{1-a^2}<|a|$ (the middle function is monotonic increasing, equal to $|a|$ at $0$ and $1$, and has slope 0 initially), so this pole is the only one in our integral: $$I=\\frac{4\\pi i}{a} \\left(-\\frac{i}{a}(1-\\sqrt{1-a^2})+\\frac{i}{a}(1+\\sqrt{1-a^2})\\right)^{-1}=\\frac{2\\pi}{\\sqrt{1-a^2}}$$"},
{q:"Calculate $\\int_{-\\infty}^\\infty e^{-ikx}\\tanh(x)dx$. (UCSD quals spring 2015 #19)",a:"$\\frac{-\\pi i}{\\sinh(k\\pi/2)}$. There are two tricks here: one is to throw in a regularization factor of $e^{-\\alpha x^2}$ to deal with the infinite oscillatory behavior. The next is to exploit the periodicity of tanh with period $i\\pi$. So consider the contour integral of $f(z)=e^{-ikz-\\alpha z^2}\\tanh(z)$ in a rectangle from $z=-R$ to $z=+R$ to $z=+R+i\\pi$ to $z=-R+i\\pi$ to $z=-R$. This contains a single pole at $i\\pi/2$ of residue: $e^{k\\pi/2+\\alpha \\pi^2/4}\\lim_{z\\to 0}z \\frac{\\sinh(z+i\\pi/2)}{\\cosh(z+i\\pi/2)}$. Expand using angle addition to find the limit is $\\frac{z}{\\sinh(z)}\\cosh(z)\\to 1$. So the residue is just $e^{k\\pi/2}$ after we take $\\alpha$ to zero. The vertical bars of the contour integral are exponentially suppressed, the lower horizontal bar is the integral we want, and the upper horizontal bar is $-\\int e^{-ikx+k\\pi}\\tanh(x)dx=-I e^{k\\pi}$. Overall the residue theorem says $I(1-e^{k\\pi})=2\\pi i e^{k\\pi/2}$, giving us our answer."},
{q:"Calculate $I=\\int_{\\mathbb{R}^2} \\frac{d^2 q}{2\\pi} \\frac{e^{-|q|a}}{|q|}e^{i\\vec{q}\\cdot\\vec{r}}$. (UCSD quals spring 2014 #19)",a:"$\\frac{1}{\\sqrt{a^2+r^2}}$. Switch to angular: $I=\\int_0^{2\\pi} \\int_0^\\infty \\frac{q dqd\\theta}{2\\pi} \\frac{e^{-qa}}{q}e^{iqr\\cos(\\theta)}$. The $q$ integral is trivial: $I=\\int_0^{2\\pi}\\frac{d\\theta}{2\\pi}\\frac{1}{a-ir\\cos(\\theta)}$ (you can imagine adding a regularization factor $e^{-\\alpha q}$ and then taking $\\alpha\\to 0$ to get this result). To evaluate this integral, insert $z=e^{i\\theta}$, $\\cos(\\theta)=\\frac{1}{2}(z+\\frac{1}{z})$, $d\\theta=dz/(iz)$, and simplify to find $I=\\frac{1}{\\pi r}\\int_\\gamma dz/(z^2-2\\frac{a}{ir}z+1)$. The roots are at $i \\frac{-a\\pm\\sqrt{a^2+r^2}}{r}$. The $-$ root is pretty obviously out of the unit circle, and the $+$ root is in the unit circle ($\\sqrt{a^2-r^2}-a<r$), so we can apply the residue theorem: $$I=\\frac{2\\pi i}{\\pi r}\\left(i \\frac{-a+\\sqrt{a^2+r^2}}{r}-i \\frac{-a-\\sqrt{a^2+r^2}}{r}\\right)^{-1}=\\frac{2\\pi i}{\\pi r (i/r) 2\\sqrt{a^2+r^2}=\\frac{1}{a^2+r^2}$$"},
{q:"Calculate $\\int_{-\\infty}^{\\infty}e^{-ikx}\\frac{1}{\\cosh(ax)}dx$",a:"$\\frac{\\pi}{a\\cosh(k\\pi/(2a))}$. Consider the rectangular contour integral from $-R$ to $+R$ to $R+i\\pi/a$ to $-R+i\\pi/a$ and back to $-R$. As $R\\to \\infty$ the side lengths go to zero. The residue enclosed is $e^{k\\pi/(2a)}\\lim_{z\\to 0} \\frac{z}{\\cosh(az)\\cosh(i\\pi/2)+\\sinh(az)\\sinh(i\\pi/2)}=e^{k\\pi/(2a)}\\frac{1}{ia}$. The integral on the upper part of the rectangle is just $-I e^{k\\pi/a}$. All together the residue theorem tells us that $2\\pi i e^{k\\pi/(2a)}\\frac{1}{ia}=I(1+e^{k\\pi/a})$, which simplifies to the answer."},
{q:"Calculate $\\int_{-\\infty}^{\\infty}e^{-a|x|}e^{-ikx}dx$",a:"$\\frac{2a}{a^2+k^2}$"},
{q:"What is $\\int_{-\\infty}^{\\infty}e^{-ikx}dx$",a:"$2\\pi\\delta(k)$"},
{q:"What is $\\int_{\\mathbb{R}^3} e^{-i\\vec{k}\\cdot \\vec{x}}d^3x$",a:"$\\frac{4\\pi}{|k|^2}$."},
{q:"What is $\\int_{\\mathbb{R}^2} e^{-i\\vec{k}\\cdot \\vec{x}}d^2x$",a:"$\\frac{2\\pi}{|k|}$."},
    
];
